version: "3.8"
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
   
    environment:
      DBURL: ep-autumn-shadow-a2285k10.eu-central-1.pg.koyeb.app
      DBNAME: koyebdb
      DBUSERNAME: koyeb-adm
      DBPASSWORD: npg_KgP7kCpu4mxs

